pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                dir('backend') {
                    // This will print "Hello Jenkins from Backend"
                    echo 'Hello Jenkins from the backend folder'
                    // Add your build steps here, e.g., running npm install or npm build
                }
            }
        }

        stage('Setup') {
            steps {
                script {
                    // Fetch the SonarQube token from credentials
                    env.SONAR_TOKEN = credentials('SONAR') // Replace with your credentials ID for the token
                    env.PROJECT_KEY = credentials('PROJECT_KEY') // Replace with your actual project key

                    // Echo the SonarQube token and project key for debugging
                    echo "SonarQube Token: ${env.SONAR_TOKEN}"
                    echo "SonarQube Project Key: ${env.PROJECT_KEY}"
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                
                script {
                    // This assumes you have set up a SonarQube server in Jenkins
                    def scannerHome = tool 'SonarQube Scanner' // The name of the SonarQube scanner tool
                    withSonarQubeEnv('Backend') { // The name you used for the SonarQube server
                             
                            sh """
                             ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.login=${SONAR_TOKEN} \
                            -Dsonar.projectKey=${PROJECT_KEY} \
                            -Dsonar.sources=./backend
                             """

                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 1, unit: 'HOURS') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }
}
